#!/usr/bin/env python3
import sys
import json

with open(sys.argv[1]) as f:
    authorsJson = json.load(f)
for i,e in enumerate(authorsJson):
    print(rf"\newcommand{{\orcidauthor{chr(65+i)}}}{{{e['orcid']}}}")
print(r"\Author{", end="")
for index,e in enumerate(authorsJson):
    n = index + 1
    print(f"{e['name']} $^{{{n}}}$\\orcid{chr(65+index)}{{}}", end="")
    if len(authorsJson) - 1 == index:
        pass
    elif len(authorsJson) - 1 == index + 1:
        print(" and ", end="")
    else:
        print(", ", end="")
print("}")
print(r"\AuthorNames{", end="")
for index,e in enumerate(authorsJson):
    print(e['name'], end="")
    if (len(authorsJson) - 1) == index:
        pass
    elif (len(authorsJson) - 1) == index + 1:
        print(" and ", end="")
    else:
        print(", ", end="")
print("}")
print(r"\address{%")
for index,e in enumerate(authorsJson):
    n = index + 1
    print(f"$^{n}$ \\quad {e['aff_department']}, {e['aff_name']}, {e['aff_street']}, {e['aff_city']}; {e['email']}", end="")
    if len(authorsJson) - 1 != index:
        print(r"\\")
print("}")
